# To create and activate, run:
#     conda env create -f environment.yml
#     conda activate xtralite-dev
# See README.md for more.
name: xtralite-dev
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - numpy
  - netcdf4
  - dask
  - xarray
